name: flutter_typeahead
version: 5.2.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

description: A highly customizable typeahead (autocomplete) text input field for Flutter
homepage: https://github.com/AbdulRahmanAlHamali/flutter_typeahead

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: 
    git:
      url: https://github.com/DanielAndresClavijo/flutter_keyboard_visibility.git
      path: flutter_keyboard_visibility
      ref: master
  pointer_interceptor: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
